# Use a minimal Python 3.10 image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

Run pip install torch==2.1.0
Run pip install sentence-transformers
Run pip install flask
Run pip install requests

Run pip install pytesseract
Run pip install openai

COPY llm_utils.py task_handler.py automation_agent.py .

# Expose the required port (if using Flask)
EXPOSE 8000

# Command to run the Flask application
CMD ["python", "automation_agent.py"]
